### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by YammyToast** [Lynx-At0Mic/OOProgramingAssignment1#1]
# Code Review

## Methods and Classes
+) Usage of methods as well as classes is good, with suitable naming for both. 
+) There's a necessary amount of encapsulation present in the 'custom class', and it makes sense where used. 
+) Good use of the Object Oriented Programming system. 👍 

=) Custom class and methods have been implemented well. The checklist says to 'point it out with comments', and even though its 
      pretty obvious that you've added it, just make sure its 100% clear.

## General Coding and Standards
+) Variable Naming is good and reflects what the variable holds.
+) Consistency in naming scheme (camel-case and whatnot).

+) Comments where used are good and give a lot of information about the associated code.

-) Commenting isn't present throughout the entirety of the code. This isn't too much of a problem, however I'm not sure what the class 'AnalysisTool' does for the program. (Also potentially add the 'function description' comments to this class as well).

=) Although it isn't necessary in any regard, the function description comments are very similar in style to the way in which XML documentation can be done. For example:
![image](https://user-images.githubusercontent.com/57455904/159749439-1a8acb59-a674-4791-b0c3-e381099dc453.png)

=) Which, if supported by your IDE, creates little tooltips like this:
![image](https://user-images.githubusercontent.com/57455904/159749693-bcaa06bc-92cf-4975-b948-0c09ed924067.png)

=) Again, this isn't necessary as the descriptions you give are already good, just thought I'd share. 😃 

## Error Handling

+) Error handling on the 'choice selection' (manual or file input) is solid, and I couldn't find any way to break it.

### Manual Input

Given Input:
`One Two Three Four Five Six Se*ven`

| Type     | Expected | Output |
| ----------- | ----------- | -----------|
|  Sentences     | 1       | 1 |
| Vowels   | 11        |  12 |
| Consonants | 13 | 15 |
| Upper | 7 | 7 |
| Lower | 17 | 20|

The program doesn't seem to stop reading at the asterisk, and ends up including the characters after this. As far as I can tell from the brief it needs to stop at the asterisk. (I might be wrong)

### File Input

Given Input:
` Empty Space `

Error:
![image](https://user-images.githubusercontent.com/57455904/159796020-4d1b64d6-5634-45ba-8ba9-8094af2531f4.png)

The file 'pathing' just needs some input validation on it, to check that it is neither empty, or points to a file that doesn't exist.

Given Input:
```
Object Oriented programming is a programming paradigm that relies on the concept of classes and objects.  A class is an abstract blueprint used to create more specific, concrete objects. Classes often represent broad categories, like Car or Dog that share attributes. These classes define what attributes an instance of this type will have, like colour, but not the value of those attributes for a specific object. Classes can also contain functions, called methods available only to objects of that type. These functions are defined within the class and perform some action helpful to that specific type of object.*

*Test Data:
Sentences:	6
Total Characters: 506
Vowels: 189		
Upper Case:	9
Lower Case: 497

*Doesn't include punctuation or whitespaces between words.
```

| Type     | Expected | Output |
| ----------- | ----------- | -----------|
|  Sentences     | 6       | 7 |
| Vowels   | 189        |  229 |
| Consonants | 317 | 382 |
| Upper | 9 | 20 |
| Lower | 497 | 591 |

This is likely the same issue as the manual text input, in that the 'reader' doesn't stop at the asterisk, and instead reads everything given.

----
James Hardy - 25629749

**Comment by Lynx-At0Mic** [comment]
Thank you for the code review! C# is still quite new to me so this feedback helps a lot. I'll get some changes implemented asap
