### ISSUE TITLE
Code Review (Bartosz Wilkowski 19697964)

### ISSUE THREAD

**Issue by BartoszWilkowski88** [Lynx-At0Mic/OOProgramingAssignment1#3]
# Code Review (Bartosz Wilkowski 19697964)
This review is for the whole program rather than each class as I personally couldn't find enough issues to speak about each class individually. In fact I only found issues during runtime of the program and couldn't find any coding improvements aside from the errors which I found.
## Errors
When trying to enter text from a file I entered blank when asked for file path and it broke the program.
![image](https://user-images.githubusercontent.com/102090465/160050838-28d8901b-2450-4b46-8452-24ee5f2a4683.png)
You handled errors with Try and Catch well however, in this case the program crashes before it reaches the Catch. The way I handled that error in my code is using a Guard Clause however, I solved it within your code by adding an if statement just before the error:
![image](https://user-images.githubusercontent.com/102090465/160051828-45343de5-9c0c-4af2-9bde-21473b5ac1d3.png)

Next I attempted running an analysis on the pre-set example file from blackboard and it looks like it doesn't stop at the asterisk therefore, outputted incorrect data.
![image](https://user-images.githubusercontent.com/102090465/160052209-39b0045a-5f79-473a-98f3-14419817fc37.png)
I then created a test file and gave it a run, just like my program it treats ellipsis as 3 sentences. Since I haven't resolved this issue in my program yet I don't have any suggestions. Once again to back up the previous error, the program didn't treat the asterisk as an end of entry.
![image](https://user-images.githubusercontent.com/102090465/160052446-e38c7531-2256-476d-921f-2516dcb5fda0.png)
I tried using ellipsis and asterisk again in manual input and it seems to be handling it perfectly, couldn't find an issue, seems like you know what you're doing but simply forgot or haven't yet implemented the same handling to file input.

## Side notes

- Your program doesn't include total characters, I do not know if this is required or not however, in the pre-set example file it has a total characters entry so I thought I'd let you know just in case you're like me and want to add it.

- Your program also doesn't seem to store long words as specified in the brief.

![image](https://user-images.githubusercontent.com/102090465/160054198-543e7d5e-f706-46f2-aaea-0dbb37d2a7c5.png)
To my understanding its not required to get pass and 2:2 standard however, I believe if you want higher than that then it is required (I could be wrong!) If my assumption is correct though, I strongly recommend you do it as you in my opinion have a first standard piece of work right here.

## Positives

- Excellent commenting, I particularly liked your commenting within code, see example below. I've always left my comments above code as a chunk describing the whole code rather than using your way to make a lot of small comments within code. It certainly makes code clearer and easier to understand.

![image](https://user-images.githubusercontent.com/102090465/160053770-ff934048-3c27-47f2-a7f4-0f3287ead51d.png)

- You also use methods and classes exceptionally well, you appropriately used data abstraction to separate private and public code.

## Conclusion
Small details either missed or simply not added yet as you have clearly shown you know what you're doing and to my belief nothing that you need to add is new e.g. your manual text handling is perfect and you simply need to do the same for file input. 
In general, solid piece of work that despite my hard efforts I was only able to find a couple of errors within.
I would personally add 3 things to your program 1. Display amount of total characters. 2. Add a 4th option to the program which loads the pre-set example file. and 3. Long words file generator. See brief.
As for suggestions to improve the code itself, I can't think of any for this piece of work, you've clearly put in a lot of work that makes the program function the way that brief specifies (aside from long words) and you did it with some great coding that is well written and easy to understand. 
Good job and good luck!

**Comment by Lynx-At0Mic** [comment]
Thanks for the review! I thought I had tested my code thoroughly but obviously not since I left an unhandled exception and my regex is doing crazy unexpected things, thanks for bringing that to my attention. I had also completely forgotten to implement the long words file and total characters. Thanks again for the review, I'll get those changes implemented 👍

**Comment by Lynx-At0Mic** [comment]
Fixed in #2
